prompts = [
    "The best name for a pet rock.",
    "A new word for something that is totally useless.",
    "The worst thing to find in your birthday cake.",
    "A bad thing to say to your date's parents.",
    "A rejected title for 'The Bible'.",
    "The worst theme for a pinball machine.",
    "A unique feature in a luxury car for dogs.",
    "The worst thing to say during a job interview.",
    "The title of a musical about your life.",
    "The worst advice a doctor could give.",
    "A creative way to use a banana.",
    "The most embarrassing thing to happen at a job interview.",
    "An unusual pizza topping.",
    "A terrible name for a hotel.",
    "An unlikely item to be passed down through generations.",
    "Something not to do in a crowded elevator.",
    "A bizarre flavor for a popsicle.",
    "The name of a new cologne for lawyers.",
    "An unusual item to bring to a movie theater.",
    "A terrible thing to carve into a tree.",
    "An unexpected item to find in a vending machine.",
    "A bad slogan for a restaurant.",
    "A strange place to hold a family reunion.",
    "An unusual ice cream flavor.",
    "A poor choice for a children's storybook character.",
    "The name of a new reality TV show about ants.",
    "The worst way to impress your crush.",
    "A bizarre ingredient for a salad.",
    "The worst title for a romantic comedy.",
    "An odd way to greet someone.",
    "A surprising thing to find inside a sofa.",
    "An unexpected use for a toilet plunger.",
    "A terrible name for a boat.",
    "A weird item to bring to a job interview.",
    "The worst flavor for a toothpaste.",
    "An unusual way to celebrate a birthday.",
    "A terrible name for a sports team.",
    "The worst thing to receive as a birthday gift.",
    "A strange thing to find in a time capsule.",
    "An unusual name for a street.",
    "The worst way to start a conversation.",
    "A bizarre use for a paperclip."
]
